"""Derive reel-vertical.html (1080x1920, Reels / Stories / LinkedIn) from reel.html (1920x1080, the site film v3).

Same timeline, same scenes, same cues (so the same score); the composition is redone for a tall frame:
  - the 3D world is seen with the camera turned 90 degrees (yaw + 90), so the business and the straight workflow run
    top to bottom instead of left to right; the light and the shadows turn with the camera, so the shading looks the same;
  - the focal length is set per camera key (fov is vertical) so the subject fits 1080 px wide;
  - step labels sit to the right of the straight workflow, the approval card to its left;
  - every headline is re-broken onto more lines inside the safe area (120 px top and bottom, 80 px sides);
  - the connector becomes a vertical chain; the end card is a centred stack.
Every replacement is asserted, so a change to reel.html that breaks the mapping fails loudly instead of rendering a
wrong frame. Never edit reel-vertical.html by hand: edit reel.html (or this file), then re-run.
Usage: python video/reel/v3/make_vertical.py
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
s = (HERE / "reel.html").read_text(encoding="utf-8")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, f"expected {count}x, found {n}: {old[:100]!r}"
    s = s.replace(old, new)


# composition constants for the tall frame
CX = 540            # horizontal centre
MCP_Y = 1041        # centre of the connector chain (the MCP pill)
IRIS_Y = 981        # where the iris closes and the end-card orb starts (60 px above the pill, as in the source)

# ---------------------------------------------------------------- head + CSS
rep("<title>lumic — 40-second film (v3)</title>", "<title>lumic — 40-second film (v3), vertical</title>")
rep("  lumic film v3. 1920x1080, 40 s.",
    "  GENERATED by make_vertical.py from reel.html: the VERTICAL cut (1080x1920) for Reels, Stories and LinkedIn.\n"
    "  Do not edit this file; edit reel.html or make_vertical.py and re-run. Rendered by render.py --v3 --vertical.\n"
    "  lumic film v3. 1920x1080, 40 s.")
rep("#stage{position:absolute;left:0;top:0;width:1920px;height:1080px;", "#stage{position:absolute;left:0;top:0;width:1080px;height:1920px;")
rep(".layer{position:absolute;left:0;top:0;width:1920px;height:1080px;transform-origin:0 0}", ".layer{position:absolute;left:0;top:0;width:1080px;height:1920px;transform-origin:0 0}")
rep("#w3{position:absolute;left:0;top:0;width:1920px;height:1080px}", "#w3{position:absolute;left:0;top:0;width:1080px;height:1920px}")
rep(".ln.center{left:0;width:1920px;text-align:center}", ".ln.center{left:0;width:1080px;text-align:center}")
rep(".h{font-size:76px;", ".h{font-size:80px;")
rep(".hx{font-size:88px;", ".hx{font-size:100px;")
rep(".sub{font-size:30px;", ".sub{font-size:34px;")
rep("#scrim{background:linear-gradient(180deg,rgba(255,255,255,.96) 0%,rgba(255,255,255,.9) 22%,rgba(255,255,255,0) 40%)}",
    "#scrim{background:linear-gradient(180deg,rgba(255,255,255,.96) 0%,rgba(255,255,255,.9) 24%,rgba(255,255,255,0) 36%)}")
rep("#scrimL{background:linear-gradient(90deg,rgba(255,255,255,.97) 0%,rgba(255,255,255,.92) 30%,rgba(255,255,255,0) 52%)}",
    "#scrimL{background:linear-gradient(180deg,rgba(255,255,255,.97) 0%,rgba(255,255,255,.92) 18%,rgba(255,255,255,0) 30%)}")
rep(".cnt{position:absolute;font-size:23px;", ".cnt{position:absolute;font-size:28px;")
rep(".capx{position:absolute;font-size:15px;", ".capx{position:absolute;font-size:17px;")
rep("box-shadow:var(--sh);padding:16px 18px;transform-origin:50% 100%}", "box-shadow:var(--sh);padding:16px 18px;transform-origin:100% 50%}")

# ---------------------------------------------------------------- canvas + svg sizes
rep('<canvas id="w3" width="1920" height="1080"></canvas>', '<canvas id="w3" width="1080" height="1920"></canvas>')
rep('<svg id="rs" class="abs" width="1920" height="1080" viewBox="0 0 1920 1080">', '<svg id="rs" class="abs" width="1080" height="1920" viewBox="0 0 1080 1920">')
rep('<circle id="r1" cx="960" cy="540"', f'<circle id="r1" cx="{CX}" cy="960"')
rep('<circle id="r2" cx="960" cy="540"', f'<circle id="r2" cx="{CX}" cy="960"')
rep('<svg id="conn" class="abs" width="1920" height="1080" viewBox="0 0 1920 1080">', '<svg id="conn" class="abs" width="1080" height="1920" viewBox="0 0 1080 1920">')
rep('<svg id="rs9" class="abs" width="1920" height="1080" viewBox="0 0 1920 1080">', '<svg id="rs9" class="abs" width="1080" height="1920" viewBox="0 0 1080 1920">')
rep('<svg id="irisR" class="abs" width="1920" height="1080" viewBox="0 0 1920 1080">', '<svg id="irisR" class="abs" width="1080" height="1920" viewBox="0 0 1080 1920">')

# ---------------------------------------------------------------- type, re-broken for a tall frame (copy unchanged)
rep('''      <div class="ln h" id="t1a" style="left:150px;top:402px">Your systems hold the data.</div>
      <div class="ln h" id="t1b" style="left:150px;top:490px">Your team still does the work <em>by hand.</em></div>''',
    '''      <div class="ln h" id="t1a" style="left:80px;top:540px">Your systems</div>
      <div class="ln h" id="t1c" style="left:80px;top:632px">hold the data.</div>
      <div class="ln h" id="t1b" style="left:80px;top:756px">Your team still does</div>
      <div class="ln h" id="t1d" style="left:80px;top:848px">the work <em>by hand.</em></div>''')
rep('<div class="ln hx" id="t3a" style="left:150px;top:398px">We come in.</div>',
    '<div class="ln hx" id="t3a" style="left:80px;top:196px">We come in.</div>')
rep('<div class="ln sub" id="t3s" style="left:154px;top:508px;width:760px">',
    '<div class="ln sub" id="t3s" style="left:84px;top:322px;width:900px">')
rep('<div class="ln h" id="t4a" style="left:150px;top:118px">We learn how the work is <em>really</em> done.</div>',
    '<div class="ln h" id="t4a" style="left:80px;top:170px">We learn how the work</div>\n'
    '    <div class="ln h" id="t4b" style="left:80px;top:262px">is <em>really</em> done.</div>')
rep('<div class="ln h" id="t5a" style="left:150px;top:118px">We automate it, with AI <em>where it fits.</em></div>',
    '<div class="ln h" id="t5a" style="left:80px;top:170px">We automate it,</div>\n'
    '    <div class="ln h" id="t5b" style="left:80px;top:262px">with AI <em>where it fits.</em></div>')
rep('<div class="ln sub" id="t5s" style="left:154px;top:218px;width:1000px">',
    '<div class="ln sub" id="t5s" style="left:84px;top:378px;width:900px">')
rep('<div class="ln" id="t6c" style="left:152px;top:128px;font-size:52px;letter-spacing:-.022em;line-height:1.1">Each AI agent runs on its own <em>dedicated computer.</em></div>',
    '<div class="ln" id="t6c" style="left:80px;top:170px;font-size:68px;letter-spacing:-.022em;line-height:1.1">Each AI agent runs</div>\n'
    '    <div class="ln" id="t6d" style="left:80px;top:250px;font-size:68px;letter-spacing:-.022em;line-height:1.1">on its own <em>dedicated computer.</em></div>')
rep('<div class="ln h" id="t6a" style="left:150px;top:118px">And we keep it <em>working.</em></div>',
    '<div class="ln h" id="t6a" style="left:80px;top:170px">And we keep it</div>\n'
    '    <div class="ln h" id="t6b" style="left:80px;top:262px"><em>working.</em></div>')
rep('<div class="ln sub" id="t6s" style="left:154px;top:218px;width:1100px">',
    '<div class="ln sub" id="t6s" style="left:84px;top:378px;width:900px">')
rep('<div class="ln h" id="t7a" style="left:150px;top:118px">In production, <em>every day.</em></div>',
    '<div class="ln h" id="t7a" style="left:80px;top:170px">In production,</div>\n'
    '    <div class="ln h" id="t7b" style="left:80px;top:262px"><em>every day.</em></div>')
rep('<div class="ln sub" id="t7s" style="left:154px;top:218px;width:1000px">',
    '<div class="ln sub" id="t7s" style="left:84px;top:378px;width:900px">')
rep('<div class="cnt" id="cntA" style="left:150px;top:944px">', '<div class="cnt" id="cntA" style="left:80px;top:1690px">')
rep('<div class="cnt" id="cntB" style="left:150px;top:944px;color:var(--pd)">', '<div class="cnt" id="cntB" style="left:80px;top:1690px;color:var(--pd)">')
rep('<div class="capx" id="capD" style="right:150px;top:150px">', '<div class="capx" id="capD" style="right:80px;top:1700px">')

# ---------------------------------------------------------------- the connector (dark): a vertical chain
rep('<line id="cln0" x1="755" y1="620" x2="870" y2="620"', f'<line id="cln0" x1="{CX}" y1="924" x2="{CX}" y2="924"')
rep('<line id="cln1" x1="1050" y1="620" x2="1165" y2="620"', f'<line id="cln1" x1="{CX}" y1="1072" x2="{CX}" y2="1072"')
rep('<div class="dpill" id="soon" style="left:0;top:262px">', '<div class="dpill" id="soon" style="left:0;top:480px">')
rep('<div class="ln center dkl" id="t8a" style="top:324px;font-size:76px;letter-spacing:-.028em">The tool we bring into <em>every job.</em></div>',
    '<div class="ln center dkl" id="t8a" style="top:552px;font-size:84px;letter-spacing:-.028em">The tool we bring into</div>\n'
    '    <div class="ln center dkl" id="t8c" style="top:644px;font-size:84px;letter-spacing:-.028em"><em>every job.</em></div>')
rep('<div class="dcard" id="dcA" style="left:405px;top:558px">', '<div class="dcard" id="dcA" style="left:365px;top:800px">')
rep('<div class="dcard" id="dcS" style="left:1165px;top:558px">', '<div class="dcard" id="dcS" style="left:365px;top:1158px">')
rep('<div class="dtag" id="dtag" style="left:0;top:708px">', '<div class="dtag" id="dtag" style="left:0;top:1318px">')
rep('<div class="ln center dsub" id="t8b" style="top:806px;font-size:24px;font-weight:400">Connect any AI to your systems. Built into every job we do.</div>',
    '<div class="ln center dsub" id="t8b" style="top:1416px;font-size:30px;font-weight:400">Connect any AI to your systems.</div>\n'
    '    <div class="ln center dsub" id="t8d" style="top:1460px;font-size:30px;font-weight:400">Built into every job we do.</div>')

# ---------------------------------------------------------------- end card: a centred stack
rep('<div class="wmk" id="wmEnd" style="font-size:190px">', '<div class="wmk" id="wmEnd" style="font-size:220px">')
rep('<div class="ln center" id="t9a" style="top:600px;font-size:44px;letter-spacing:-.015em;color:var(--text);font-weight:400">AI, deployed into your business and <em>kept working.</em></div>',
    '<div class="ln center" id="t9a" style="top:1000px;font-size:56px;letter-spacing:-.015em;color:var(--text);font-weight:400">AI, deployed into your business</div>\n'
    '    <div class="ln center" id="t9c" style="top:1070px;font-size:56px;letter-spacing:-.015em;color:var(--text);font-weight:400">and <em>kept working.</em></div>')
rep('<div class="ln center" id="t9b" style="top:696px;font-size:21px;', '<div class="ln center" id="t9b" style="top:1186px;font-size:26px;')

# ---------------------------------------------------------------- JS: the 3D world, turned 90 degrees for the tall frame
rep("const W = 1920, H = 1080;", "const W = 1080, H = 1920;")
rep('''const CK = [
  { t: 0.0, tx: 0, ty: 0, tz: 0, dist: 2700, yaw: 0, pitch: 90, fov: 24, sx: 960, sy: 540 },
  { t: 3.85, tx: 0, ty: 0, tz: 0, dist: 2700, yaw: 0, pitch: 90, fov: 24, sx: 960, sy: 540 },
  { t: 5.4, tx: 30, ty: 0, tz: 0, dist: 2350, yaw: -15, pitch: 50, fov: 24, sx: 980, sy: 660, c: 1 },
  { t: 6.9, tx: 30, ty: 0, tz: 0, dist: 2250, yaw: -7, pitch: 47, fov: 24, sx: 990, sy: 660, c: 1 },
  { t: 9.6, tx: -440, ty: 120, tz: 0, dist: 1600, yaw: 12, pitch: 30, fov: 26, sx: 1250, sy: 600, c: 1 },
  { t: 13.4, tx: 40, ty: 20, tz: 0, dist: 2650, yaw: 22, pitch: 55, fov: 24, sx: 960, sy: 650, c: 1 },
  { t: 15.0, tx: 0, ty: 0, tz: 0, dist: 2550, yaw: 4, pitch: 42, fov: 24, sx: 960, sy: 690 },
  { t: 16.9, tx: 110, ty: 0, tz: 0, dist: 2200, yaw: 6, pitch: 39, fov: 24, sx: 960, sy: 690 },
  { t: 18.3, tx: 0, ty: -60, tz: 0, dist: 2550, yaw: 2, pitch: 42, fov: 24, sx: 960, sy: 670, c: 1 },
  { t: 20.4, tx: 0, ty: -360, tz: 60, dist: 1300, yaw: -10, pitch: 16, fov: 26, sx: 960, sy: 640, c: 1 },
  { t: 23.0, tx: 0, ty: -370, tz: 60, dist: 1420, yaw: -2, pitch: 20, fov: 26, sx: 960, sy: 650, c: 1 },
  { t: 26.3, tx: 0, ty: -360, tz: 0, dist: 2350, yaw: 24, pitch: 40, fov: 25, sx: 1060, sy: 660, c: 1 },
  { t: 29.6, tx: 0, ty: -200, tz: 0, dist: 9000, yaw: 36, pitch: 58, fov: 30, sx: 960, sy: 660, c: 1 },
  { t: 32.0, tx: 0, ty: -200, tz: 0, dist: 9600, yaw: 40, pitch: 61, fov: 30, sx: 960, sy: 630 }
];''', '''// vertical cut: the same moves turned 90 degrees (yaw + 90), so the long axis of the business runs down the frame;
// fov is vertical, so it is wider here to keep the subject the right size across 1080 px
const CK = [
  { t: 0.0, tx: 0, ty: 0, tz: 0, dist: 2700, yaw: 90, pitch: 90, fov: 41, sx: 540, sy: 960 },
  { t: 3.85, tx: 0, ty: 0, tz: 0, dist: 2700, yaw: 90, pitch: 90, fov: 41, sx: 540, sy: 960 },
  { t: 5.4, tx: 30, ty: 0, tz: 0, dist: 2350, yaw: 75, pitch: 50, fov: 42, sx: 540, sy: 1160, c: 1 },
  { t: 6.9, tx: 30, ty: 0, tz: 0, dist: 2250, yaw: 83, pitch: 47, fov: 42, sx: 540, sy: 1130, c: 1 },
  { t: 9.6, tx: -520, ty: 20, tz: 0, dist: 1650, yaw: 96, pitch: 32, fov: 48, sx: 540, sy: 1060, c: 1 },
  { t: 13.4, tx: 40, ty: 20, tz: 0, dist: 2650, yaw: 102, pitch: 55, fov: 45, sx: 540, sy: 1050, c: 1 },
  { t: 15.0, tx: 0, ty: 0, tz: 0, dist: 2550, yaw: 94, pitch: 42, fov: 38, sx: 520, sy: 1070 },
  { t: 16.9, tx: 110, ty: 0, tz: 0, dist: 2200, yaw: 96, pitch: 39, fov: 38, sx: 520, sy: 1070 },
  { t: 18.3, tx: 0, ty: -60, tz: 0, dist: 2550, yaw: 88, pitch: 42, fov: 40, sx: 520, sy: 1070, c: 1 },
  { t: 20.4, tx: 0, ty: -360, tz: 60, dist: 1300, yaw: 40, pitch: 22, fov: 42, sx: 540, sy: 1150, c: 1 },
  { t: 23.0, tx: 0, ty: -370, tz: 60, dist: 1420, yaw: 48, pitch: 31, fov: 50, sx: 540, sy: 1150, c: 1 },
  { t: 26.3, tx: 0, ty: -360, tz: 0, dist: 2350, yaw: 74, pitch: 40, fov: 46, sx: 540, sy: 1100, c: 1 },
  { t: 29.6, tx: 0, ty: -200, tz: 0, dist: 9000, yaw: 86, pitch: 58, fov: 50, sx: 540, sy: 1000, c: 1 },
  { t: 32.0, tx: 0, ty: -200, tz: 0, dist: 9600, yaw: 90, pitch: 61, fov: 50, sx: 540, sy: 960 }
];''')
# the light and the shadows turn with the camera ((x, y) -> (-y, x)), so every face is shaded as in the source
rep("const LIGHT = (() => { const v = [-.45, -.55, .7]", "const LIGHT = (() => { const v = [.55, -.45, .7]")
rep("const s = 1.18, ox = 14, oy = 18;", "const s = 1.18, ox = -18, oy = 14;")
rep("const sp = [[c.x - c.w * .55 + 10, c.y - c.d * .55 + 14], [c.x + c.w * .55 + 10, c.y - c.d * .55 + 14], [c.x + c.w * .55 + 10, c.y + c.d * .55 + 14], [c.x - c.w * .55 + 10, c.y + c.d * .55 + 14]]",
    "const sp = [[c.x - c.w * .55 - 14, c.y - c.d * .55 + 10], [c.x + c.w * .55 - 14, c.y - c.d * .55 + 10], [c.x + c.w * .55 - 14, c.y + c.d * .55 + 10], [c.x - c.w * .55 - 14, c.y + c.d * .55 + 10]]")
# the computer's status light sits on the face the camera sees (+x here)
rep("FR.led = [CUBE.x, CUBE.y - CUBE.d / 2 - .5, h * .5];", "FR.led = [CUBE.x + CUBE.w / 2 + .5, CUBE.y, h * .5];")
rep("const led = FR.led || [CUBE.x, CUBE.y - CUBE.d / 2, CUBE.h / 2];", "const led = FR.led || [CUBE.x + CUBE.w / 2, CUBE.y, CUBE.h / 2];", count=2)
rep("const led = [CUBE.x, CUBE.y - CUBE.d / 2 - .5, CUBE.h * .5];", "const led = [CUBE.x + CUBE.w / 2 + .5, CUBE.y, CUBE.h * .5];")

# ---------------------------------------------------------------- JS: text line registry (the new line ids)
rep("line('t1a', 1.12, S.s2 + 2.3, .05);", "line('t1a', 1.12, S.s2 + 2.3, .05); line('t1c', 1.22, S.s2 + 2.3, .05);")
rep("line('t1b', 1.5, S.s2 + 2.3, .042);", "line('t1b', 1.5, S.s2 + 2.3, .042); line('t1d', 1.668, S.s2 + 2.3, .042);")
rep("line('t4a', S.s4 + .15, S.s5 - .45, .045);", "line('t4a', S.s4 + .15, S.s5 - .45, .045); line('t4b', S.s4 + .375, S.s5 - .45, .045);")
rep("line('t5a', S.s5 + .25, S.s5 + 4.5, .045);", "line('t5a', S.s5 + .25, S.s5 + 4.5, .045); line('t5b', S.s5 + .385, S.s5 + 4.5, .045);")
rep("line('t6c', S.s6 + 1.55, S.s6 + 3.35, .03);", "line('t6c', S.s6 + 1.55, S.s6 + 3.35, .03); line('t6d', S.s6 + 1.67, S.s6 + 3.35, .03);")
rep("line('t6a', S.s6b + .75, S.s7 - .05, .05);", "line('t6a', S.s6b + .75, S.s7 - .05, .05); line('t6b', S.s6b + .95, S.s7 - .05, .05);")
rep("line('t7a', S.s7 + .75, S.s8 - .35, .05);", "line('t7a', S.s7 + .75, S.s8 - .35, .05); line('t7b', S.s7 + .85, S.s8 - .35, .05);")
rep("line('t8a', S.s8 + 1.4, S.s8 + 4.2, .05);", "line('t8a', S.s8 + 1.4, S.s8 + 4.2, .05); line('t8c', S.s8 + 1.65, S.s8 + 4.2, .05);")
rep("line('t8b', S.s8 + 2.45, S.s8 + 4.2, .02);", "line('t8b', S.s8 + 2.45, S.s8 + 4.2, .02); line('t8d', S.s8 + 2.57, S.s8 + 4.2, .02);")
rep("line('t9a', S.s9 + 1.85, 99, .026, .95);", "line('t9a', S.s9 + 1.85, 99, .026, .95); line('t9c', S.s9 + 1.98, 99, .026, .95);")
# night colour shift on both lines of the scale headline
rep("  $('t7a').style.color = mix('#0f172a', '#ffffff', lt);\n"
    "  qs($('t7a'), '.emw') && $('t7a').querySelectorAll('.emw').forEach(e => { e.style.color = mix('#4845c2', '#a5a4f3', lt); });",
    "  ['t7a', 't7b'].forEach(id => { $(id).style.color = mix('#0f172a', '#ffffff', lt);\n"
    "    $(id).querySelectorAll('.emw').forEach(e => { e.style.color = mix('#4845c2', '#a5a4f3', lt); }); });")

# ---------------------------------------------------------------- JS: labels in the world
# step labels: above each block while the business is scattered; to the right of the block once it is one workflow
rep('''    const [sx, sy, , k] = pj(st.x, st.y, st.z + st.h + 46 + stackCount(i, t) * 4.2 + (i % 2) * 70 * m);
    const sc = clamp(k * .92, .62, 1.15) * lerp(1, .88, m);
    const lit = tourTime(i) <= t && t < tourTime(i) + .5 ? 1 : 0;
    tr(c, sx - c.offsetWidth / 2, sy - c.offsetHeight, sc * (1 + .06 * lit));''',
    '''    const [sx, sy, , k] = pj(st.x, st.y, st.z + st.h + 46 + stackCount(i, t) * 4.2);
    const [rx, ry, , rk] = pj(st.x, st.y + st.d / 2 + 22, st.z + st.h * .5);
    const sc = lerp(clamp(k * .92, .62, 1.15), clamp(rk * .92, .62, 1.15) * .88, m);
    const lit = tourTime(i) <= t && t < tourTime(i) + .5 ? 1 : 0;
    const cw = c.offsetWidth, chh = c.offsetHeight;                      // origin is bottom centre: place the scaled box
    tr(c, lerp(sx - cw / 2, rx - cw / 2 * (1 - sc), m), lerp(sy - chh, ry - chh + chh * sc / 2, m), sc * (1 + .06 * lit));
    const ccx = lerp(sx, rx + cw * sc / 2, m), ccy = lerp(sy - chh * sc / 2, ry, m);   // a label whose block leaves the frame fades at the edge
    const edge = clamp((Math.min(ccx - cw * sc / 2, W - ccx - cw * sc / 2, H - 110 - ccy) - 16) / 40);''')
# fold the edge fade into the chip opacity
rep("    op(c, a);\n    c.style.borderColor", "    op(c, a * edge);\n    c.style.borderColor")
# timestamps: same edge fade
rep("    tr(ts, tx - ts.offsetWidth / 2, ty + 6 * (1 - tw(t, reach, reach + .5)), clamp(kk, .7, 1.05));\n"
    "    op(ts, P(t, reach, reach + .3) * (1 - tw(t, S.s5 - .4, S.s5 - .1, E.lin)));",
    "    tr(ts, tx - ts.offsetWidth / 2, ty + 6 * (1 - tw(t, reach, reach + .5)), clamp(kk, .7, 1.05));\n"
    "    const tse = clamp((Math.min(tx - ts.offsetWidth / 2, W - tx - ts.offsetWidth / 2, H - 110 - ty) - 16) / 40);\n"
    "    op(ts, tse * P(t, reach, reach + .3) * (1 - tw(t, S.s5 - .4, S.s5 - .1, E.lin)));")
# timestamps sit in front of each block (toward the camera, +x here)
rep("const [tx, ty, , kk] = pj(st.x, st.y - st.d / 2 - 46, 0);", "const [tx, ty, , kk] = pj(st.x + st.w / 2 + 40, st.y, 0);")
# the approval card stands to the left of the person's step (origin: right middle)
rep('''    const [sx, sy, , k] = pj(st3.x, st3.y, st3.z + st3.h + 120);
    tr(ap, sx - 140, sy - ap.offsetHeight - 30 * (1 - apIn), clamp(k, .8, 1.2) * Math.max(0, lerp(.85, 1, apIn)));''',
    '''    const [sx, sy, , k] = pj(st3.x, st3.y - st3.d / 2 - 30, st3.z + st3.h * .5);
    tr(ap, sx - ap.offsetWidth, sy - ap.offsetHeight / 2 + 30 * (1 - apIn), clamp(k, .8, 1.2) * Math.max(0, lerp(.85, 1, apIn)));''')

# the monthly checks stay inside the frame
rep("    tr(d, sx - d.offsetWidth / 2, sy - d.offsetHeight, clamp(k, .75, 1.1) * Math.max(0, lerp(.7, 1, pin)));",
    "    const mw = d.offsetWidth * clamp(k, .75, 1.1) / 2, mcx = clamp(sx, 50 + mw, W - 50 - mw);\n"
    "    tr(d, mcx - d.offsetWidth / 2, sy - d.offsetHeight, clamp(k, .75, 1.1) * Math.max(0, lerp(.7, 1, pin)));")

# ---------------------------------------------------------------- JS: 2D scenes
# ignition flare
rep("const fl = $('flare'), fw = 1000 * tw(t, .03, .6, E.outExpo);", "const fl = $('flare'), fw = 900 * tw(t, .03, .6, E.outExpo);")
rep("tr(fl, 960 - fw / 2, FR.orbScreen ? FR.orbScreen[1] : 540);", f"tr(fl, {CX} - fw / 2, FR.orbScreen ? FR.orbScreen[1] : 960);")
# the connector: iris, glow, chain
rep("$('dark').style.clipPath = `circle(${f2(Math.max(0, R))}px at 960px 560px)`;", f"$('dark').style.clipPath = `circle(${{f2(Math.max(0, R))}}px at {CX}px {IRIS_Y}px)`;")
rep("irisC.setAttribute('cx', 960); irisC.setAttribute('cy', 560);", f"irisC.setAttribute('cx', {CX}); irisC.setAttribute('cy', {IRIS_Y});")
rep("tr($('dglow'), 960, 600);", f"tr($('dglow'), {CX}, {MCP_Y - 20});")
rep("tr(dA, -50 * (1 - aIn), 0, 1 - .04 * out);", "tr(dA, 0, -40 * (1 - aIn), 1 - .04 * out);")
rep("tr(dS, 50 * (1 - bIn), 0, 1 - .04 * out);", "tr(dS, 0, 40 * (1 - bIn), 1 - .04 * out);")
rep("l0.setAttribute('x2', f2(lerp(755, 870, d0))); l1.setAttribute('x2', f2(lerp(1050, 1165, d1)));",
    "l0.setAttribute('y2', f2(lerp(924, 1010, d0))); l1.setAttribute('y2', f2(lerp(1072, 1158, d1)));")
rep("const pX = p => lerp(755, 1165, p)", "const pX = p => lerp(924, 1158, p)")
rep("c.setAttribute('cx', f2(pX(pp))); c.setAttribute('cy', 620);", f"c.setAttribute('cx', {CX}); c.setAttribute('cy', f2(pX(pp)));")
rep("c.setAttribute('cx', f2(pX(clamp(pp - (k + 1) * .012)))); c.setAttribute('cy', 620);", f"c.setAttribute('cx', {CX}); c.setAttribute('cy', f2(pX(clamp(pp - (k + 1) * .012))));")
# the dark orb: it hops to the middle of the chain, becomes the MCP pill, then returns to the iris centre
rep("const [sx, sy] = FR.orbStart || [960, 600];", f"const [sx, sy] = FR.orbStart || [{CX}, 960];")
rep("let x = lerp(sx, 960, g1), y = lerp(sy, 620, g1) - 110 * Math.sin(Math.PI * g1);", f"let x = lerp(sx, {CX}, g1), y = lerp(sy, {MCP_Y}, g1) - 110 * Math.sin(Math.PI * g1);")
rep("tr(o, lerp(x, 960, back), lerp(y, 560, back));", f"tr(o, lerp(x, {CX}, back), lerp(y, {IRIS_Y}, back));")
# end card
rep("tr(o, 960, 560, lerp(44 / 48, WE.dot.w / 48, g9));", f"tr(o, {CX}, {IRIS_Y}, lerp(44 / 48, WE.dot.w / 48, g9));")
rep("WE = { x: 960 - r.w / 2, y: 330, w: r.w };", f"WE = {{ x: {CX} - r.w / 2, y: 690, w: r.w }};")
rep("WE.ox = 960 - WE.dot.x; WE.oy = 560 - WE.dot.y;", f"WE.ox = {CX} - WE.dot.x; WE.oy = {IRIS_Y} - WE.dot.y;")
rep("soon.style.left = f2(960 - soon.offsetWidth / 2) + 'px';", f"soon.style.left = f2({CX} - soon.offsetWidth / 2) + 'px';")
rep("tg.style.left = f2(960 - tg.offsetWidth / 2) + 'px';", f"tg.style.left = f2({CX} - tg.offsetWidth / 2) + 'px';")
# the top scrim stays through the scale scene (the city reaches the top of a tall frame) and leaves with the night
rep("op($('scrim'), (tw(t, S.s4 - .2, S.s4 + .3, E.lin) * (1 - tw(t, S.s7 + 1.2, S.s7 + 2.2, E.lin))) * (1 - NP));",
    "op($('scrim'), tw(t, S.s4 - .2, S.s4 + .3, E.lin) * clamp(1 - 2.5 * NP));")
# the opening headline shrinks to the top of the frame as the business rises
rep("zoom($('t1'), lerp(1, .62, mk), 150, 402, 0, lerp(0, -342, mk));", "zoom($('t1'), lerp(1, .62, mk), 80, 540, 0, lerp(0, -380, mk));")

# ---------------------------------------------------------------- preview fit
rep("K = Math.min(innerWidth / 1920, innerHeight / 1080);", "K = Math.min(innerWidth / 1080, innerHeight / 1920);")
rep("stage.style.transform = `translate(${(innerWidth - 1920 * K) / 2}px,${(innerHeight - 1080 * K) / 2}px) scale(${K})`;",
    "stage.style.transform = `translate(${(innerWidth - 1080 * K) / 2}px,${(innerHeight - 1920 * K) / 2}px) scale(${K})`;")

# nothing landscape-sized may survive
for leftover in ("width:1920px", 'width="1920"', "innerWidth / 1920", "960 -", "960, 5", "960, 6"):
    assert leftover not in s, f"a landscape size or centre survived: {leftover!r}"

out = HERE / "reel-vertical.html"
out.write_bytes(s.encode("utf-8"))                     # LF endings, as in the source
print("wrote", out)
