"""Render video/reel/reel.html (picture) + video/reel/score.py (music) into public/video/ as MP4 + WebM + poster.

The reel page must expose:
  window.DURATION      -> length in seconds (40)
  window.seek(t)       -> draw the exact frame for time t (seconds); deterministic, no wall-clock timing
  window.reelReady     -> Promise that resolves once fonts/assets are loaded

Usage:
  python3 video/reel/render.py            # full render: frames + score, 30 fps
  python3 video/reel/render.py --stills   # one PNG per second into the frames dir, for review
  python3 video/reel/render.py --music    # rebuild the score only and re-mux it into the existing videos
  python3 video/reel/render.py --v3 [--stills] [--resume] [--out DIR]   # the site film since 2026-10-01 (video/reel/v3/): picture + score locked to the
                                          # picture's own cue times (window.CUES); default output video/reel/out/v3/ for review
  python3 video/reel/render.py --v3 --vertical [--stills] [--resume] [--out DIR]
                                          # the vertical cut (1080x1920, Reels / Stories / LinkedIn): v3/reel-vertical.html (generated by
                                          # v3/make_vertical.py) + the v3 score cued from that page's window.CUES; MP4 (H.264 high) + poster
                                          # into video/reel/out/v3-vertical/ (not published on the site)
Needs: playwright (uses the installed Google Chrome), numpy, ffmpeg on PATH.
"""
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VER = "v3" if "--v3" in sys.argv else "v2" if "--v2" in sys.argv else None
V2 = VER is not None                     # the newer films: async seek + picture-driven cues
VERT = "--vertical" in sys.argv          # the v3 vertical cut (the v1 Story cut was retired on 2026-10-07)
if VERT and VER != "v3":
    sys.exit("--vertical renders the v3 vertical cut: use --v3 --vertical")
SRC = ROOT / "video" / "reel" / (("v3/reel-vertical.html" if VERT else f"{VER}/reel.html") if VER else "reel.html")
SCORE = ROOT / "video" / "reel" / (f"{VER}/score.py" if VER else "score.py")
OUT = Path(sys.argv[sys.argv.index("--out") + 1]).resolve() if "--out" in sys.argv else (
    ROOT / "video" / "reel" / "out" / (f"{VER}-vertical" if VERT else VER) if VER else ROOT / "public" / "video")
NAME = "lumic-reel-vertical" if VERT else "lumic-reel"
FPS = 30
W, H = (1080, 1920) if VERT else (1920, 1080)
TMP = Path(tempfile.gettempdir())


def shot(page, t, path):
    """Seek and capture one frame; a stalled capture is retried (frames are deterministic, so a retry is exact)."""
    for attempt in range(4):
        try:
            page.evaluate(f"window.seek({t})")
            page.screenshot(path=str(path), timeout=120000)
            return
        except Exception as e:                   # noqa: BLE001 - Playwright raises its own TimeoutError type
            if attempt == 3:
                raise
            print(f"frame at {t:.3f}s: {type(e).__name__}, retrying", flush=True)


def ff(*args):
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", *map(str, args)], check=True)


def build_score(cues: Path = None) -> Path:
    wav = TMP / "lumic-reel-score.wav"
    subprocess.run([sys.executable, str(SCORE), str(wav)] + ([str(cues)] if cues else []), check=True)
    return wav


def encode(video_in: list, wav: Path) -> None:
    """video_in: ffmpeg input args for the picture (an image sequence or an existing file)."""
    if VERT:                                     # social upload: one MP4, H.264 high profile, yuv420p, AAC 192k, faststart
        ff(*video_in, "-i", wav, "-map", "0:v:0", "-map", "1:a:0",
           "-c:v", "libx264", "-preset", "slow", "-crf", "20", "-pix_fmt", "yuv420p", "-profile:v", "high", "-level", "4.2",
           "-c:a", "aac", "-b:a", "192k", "-shortest", "-movflags", "+faststart", OUT / f"{NAME}.mp4")
        return
    ff(*video_in, "-i", wav, "-map", "0:v:0", "-map", "1:a:0",
       "-c:v", "libx264", "-preset", "slow", "-crf", "20", "-pix_fmt", "yuv420p",
       "-c:a", "aac", "-b:a", "192k", "-shortest", "-movflags", "+faststart", OUT / "lumic-reel.mp4")
    ff(*video_in, "-i", wav, "-map", "0:v:0", "-map", "1:a:0",
       "-c:v", "libvpx-vp9", "-b:v", "0", "-crf", "34", "-row-mt", "1", "-pix_fmt", "yuv420p",
       "-c:a", "libopus", "-b:a", "128k", "-shortest", OUT / "lumic-reel.webm")


def remux(wav: Path) -> None:
    for name, acodec in ((f"{NAME}.mp4", ["-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart"]),
                         (f"{NAME}.webm", ["-c:a", "libopus", "-b:a", "128k"])):
        if not (OUT / name).exists():
            continue
        src = OUT / name
        tmp = TMP / ("remux-" + name)
        ff("-i", src, "-i", wav, "-map", "0:v:0", "-map", "1:a:0", "-c:v", "copy", *acodec, "-shortest", tmp)
        shutil.move(tmp, src)


def main() -> None:
    if "--music" in sys.argv:
        remux(build_score())
        report()
        return

    from playwright.sync_api import sync_playwright

    stills = "--stills" in sys.argv
    frames = TMP / ("lumic-reel-vframes" if VERT else "lumic-reel-frames")
    if "--resume" not in sys.argv:              # --resume keeps the frames already rendered and continues
        shutil.rmtree(frames, ignore_errors=True)
    frames.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome")
        page = browser.new_page(viewport={"width": W, "height": H}, device_scale_factor=1)
        page.goto(SRC.as_uri() + "?render=1", wait_until="networkidle")
        page.evaluate("window.reelReady")
        duration = page.evaluate("window.DURATION")
        cues = None
        if V2:                                   # the score follows the picture's own cue times
            cues = TMP / "lumic-reel-cues.json"
            cues.write_text(page.evaluate("JSON.stringify(window.CUES)"))
        times = range(int(duration) + 1) if stills else range(int(duration * FPS))
        for i in times:
            t = i if stills else i / FPS
            out = frames / f"{i:05d}.png"
            if "--resume" in sys.argv and out.exists() and out.stat().st_size > 0:
                continue
            shot(page, min(t, duration - 1 / FPS), out)
        browser.close()

    if stills:
        print(f"stills in {frames}")
        return

    OUT.mkdir(parents=True, exist_ok=True)
    encode(["-framerate", FPS, "-i", frames / "%05d.png"], build_score(cues))
    ff("-i", frames / f"{int(duration * FPS) - 15:05d}.png", "-q:v", 3, OUT / f"{NAME}-poster.jpg")
    report()


def report() -> None:
    for f in sorted(OUT.iterdir()):
        print(f"{f.name}  {f.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
